[server]
database_url = "sqlite:///./data/app.db"
logging_level = "INFO"
init_user = "admin@example.com"
init_password = "password"

[server.network]
service_host_ip = "127.0.0.1"
service_host_port = 8000
use_proxy = true
proxy = "http://127.0.0.1:7890"

[fileloader.grobid]
grobid_server = "http://localhost:8070"
service = "processFulltextDocument"
batch_size = 100
sleep_time = 5
timeout = 300
coordinates = ["persName", "ref", "head", "s", "p", "title"]
multi_process = 10

[retriever.embedding]
model = "BAAI/bge-m3"
save_local = true
fp16 = true
normalize = true
device = "cuda"

[retriever.reranker]
model = "BAAI/bge-reranker-v2-m3"
save_local = true
fp16 = true
normalize = true
device = "cuda"

[retriever.knowledge_base]
store_path = "./data/knowledge_base"
doc_url = "sqlite:///./data/knowledge_base/document.db"

[retriever.knowledge_base.milvus]
uri = "http://127.0.0.1:19530"
username = ""
password = ""
token = ""
secure = false

[llm.openai]
use_proxy = true
api_key = ""

[llm.zhipu]
use_proxy = false
base_url = "https://open.bigmodel.cn/api/paas/v4/"
api_key = ""

[llm.deepseek]
use_proxy = false
base_url = "https://api.deepseek.com/v1"
api_key = ""

[tool.search]
serper_api = ""

[tool.jina]
jina_api = ""
use_loacl_model = true
model = "jinaai/ReaderLM-v2"
save_local = true
fp16 = false
device = "cuda"