"""
重写langchain的token_usage类，添加默认值
"""
from typing import Optional, NotRequired, Dict, Any, Union

from pydantic import BaseModel


class InputTokenDetails(BaseModel):
    """Breakdown of input token counts."""

    audio: int = 0
    """Audio input tokens."""

    cache_creation: int = 0
    """Input tokens that were cached and there was a cache miss.

    Since there was a cache miss, the cache was created from these tokens.
    """

    cache_read: int = 0
    """Input tokens that were cached and there was a cache hit.

    Since there was a cache hit, the tokens were read from the cache. More precisely,
    the model state given these tokens was read from the cache.
    """


class OutputTokenDetails(BaseModel):
    """Breakdown of output token counts."""

    audio: int = 0
    """Audio output tokens."""

    reasoning: int = 0
    """Reasoning output tokens.

    Tokens generated by the model in a chain of thought process (i.e. by OpenAI's o1
    models) that are not returned as part of model output.
    """


class UsageMetadata(BaseModel):
    """Usage metadata for a message, such as token counts."""

    input_tokens: int = 0
    """Count of input (or prompt) tokens. Sum of all input token types."""

    output_tokens: int = 0
    """Count of output (or completion) tokens. Sum of all output token types."""

    total_tokens: int = 0
    """Total token count. Sum of input_tokens + output_tokens."""

    input_token_details: Optional[InputTokenDetails] = InputTokenDetails()
    """Breakdown of input token counts.

    Does *not* need to sum to full input token count. Does *not* need to have all keys.
    """

    output_token_details: Optional[OutputTokenDetails] = OutputTokenDetails()
    """Breakdown of output token counts.

    Does *not* need to sum to full output token count. Does *not* need to have all keys.
    """

    @classmethod
    def create(cls, data: Optional[Union[Dict[str, Any], "UsageMetadata"]] = None) -> "UsageMetadata":
        """
        创建一个UsageMetadata实例，可以处理实际数据或None
        
        Args:
            data: 可以是字典数据、UsageMetadata实例或None
            
        Returns:
            UsageMetadata: 返回一个新的UsageMetadata实例
        """
        if data is None:
            return cls.model_construct()
        return cls.model_validate(data)
