"""
重写langchain的token_usage类，添加默认值
"""

from typing import Any, Dict, Optional, Union

from langchain_openai import ChatOpenAI
from pydantic import BaseModel


class Cost(BaseModel):
    input_price: float
    cached_price: float
    output_price: float
    is_usd: bool


GPT_4O = Cost(input_price=2.5, cached_price=1.25, output_price=10, is_usd=True)
GPT_4O_MINI = Cost(input_price=0.15, cached_price=0.075, output_price=0.6, is_usd=True)
DEEPSEEK_V3 = Cost(input_price=2, cached_price=0.5, output_price=8, is_usd=True)
DEEPSEEK_R1 = Cost(input_price=4, cached_price=1, output_price=16, is_usd=True)
GLM_4_AIR = Cost(input_price=0.5, cached_price=0.5, output_price=0.5, is_usd=False)
GLM_4_FLASH = Cost(input_price=0, cached_price=0, output_price=0, is_usd=False)


class InputTokenDetails(BaseModel):
    """Breakdown of input token counts."""

    audio: int = 0
    """Audio input tokens."""

    cache_creation: int = 0
    """Input tokens that were cached and there was a cache miss.

    Since there was a cache miss, the cache was created from these tokens.
    """

    cache_read: int = 0
    """Input tokens that were cached and there was a cache hit.

    Since there was a cache hit, the tokens were read from the cache. More precisely,
    the model state given these tokens was read from the cache.
    """


class OutputTokenDetails(BaseModel):
    """Breakdown of output token counts."""

    audio: int = 0
    """Audio output tokens."""

    reasoning: int = 0
    """Reasoning output tokens.

    Tokens generated by the model in a chain of thought process (i.e. by OpenAI's o1
    models) that are not returned as part of model output.
    """


class UsageMetadata(BaseModel):
    """Usage metadata for a message, such as token counts."""

    input_tokens: int = 0
    """Count of input (or prompt) tokens. Sum of all input token types."""

    output_tokens: int = 0
    """Count of output (or completion) tokens. Sum of all output token types."""

    total_tokens: int = 0
    """Total token count. Sum of input_tokens + output_tokens."""

    input_token_details: Optional[InputTokenDetails] = InputTokenDetails()
    """Breakdown of input token counts.

    Does *not* need to sum to full input token count. Does *not* need to have all keys.
    """

    output_token_details: Optional[OutputTokenDetails] = OutputTokenDetails()
    """Breakdown of output token counts.

    Does *not* need to sum to full output token count. Does *not* need to have all keys.
    """

    @classmethod
    def create(
        cls, data: Optional[Union[Dict[str, Any], 'UsageMetadata']] = None
    ) -> 'UsageMetadata':
        """创建一个UsageMetadata实例，可以处理实际数据或None

        Args:
            data: 可以是字典数据、UsageMetadata实例或None

        Returns:
            UsageMetadata: 返回一个新的UsageMetadata实例
        """
        if data is None:
            return cls.model_construct()
        return cls.model_validate(data)

    def calculate_cost(self, llm: ChatOpenAI) -> float:
        """计算本次调用的费用

        统一输出为人民币，若模型以美元计费，则以当前汇率进行转换

        Args:
            llm: 调用的ChatOpenAI格式大模型

        Returns:
            此次调用的总费用
        """
        if llm.model_name == 'gpt-4o-mini':
            price = GPT_4O_MINI
        elif llm.model_name in ['deepseek-chat', 'deepseek-ai/DeepSeek-V3']:
            price = DEEPSEEK_V3
        elif llm.model_name == 'deepseek-reasoner':
            price = DEEPSEEK_R1
        elif llm.model_name == 'glm-4-flash':
            price = GLM_4_FLASH
        elif llm.model_name == 'glm-4-air':
            price = GLM_4_AIR
        else:
            price = GPT_4O

        cost = (
            self.input_token_details.cache_read * price.cached_price
            + (self.input_tokens - self.input_token_details.cache_read) * price.input_price
            + self.output_tokens * price.output_price
        ) / 1000000
        if price.is_usd:
            return cost * 7.29
        return cost
